### ISSUE TITLE
US English string file doesn't get copied to the target directory

### ISSUE THREAD

**Issue by tgkokk** [HaikuArchives/Becasso#1]
OK, so in data/strings/Jamfile there isn't an entry for "US English".

That means that when the user fires up BeCasso he doesn't see the tips or anything (since the default language is US English).

When I tried to add the related line, I found out that moving files with a space in their name is difficult/impossible in Jam.

IMHO the best solution is to remove US English and just keep English.

**Comment by scottmc** [comment]
Maybe @humdingerb can look into this one?

**Comment by humdingerb** [comment]
"Fixed" with d29469b :)

**Comment by scottmc** [comment]
Thank you.  I like having color instead of colour. ;)
