### ISSUE TITLE
Add 'Share to social media' feature

### ISSUE THREAD

**Issue by ysjodha1** [HaikuArchives/Becasso#15]
A feature to share the Photos/Images created on social media would great and time-saving for the users.

**Comment by humdingerb** [comment]
FWIW, I'd much rather see a system wide service to do that. For example, a sort of fileysystem add-on that, once configured, exposes your personal social media sites etc. as a folder in the filesystem. Uploading would be as simple as saving/copying data into that folder.

**Comment by pulkomandy** [comment]
Agreed, doig this in each application makes little sense.
