### ISSUE TITLE
Need a new Icon

### ISSUE THREAD

**Issue by richienyhus** [HaikuArchives/Becasso#3]
Need a 3D app icon.

The 2D icons are ok for the time being.

**Comment by richienyhus** [comment]
Something like this in Haiku's style maybe: ![stock-photo-14478872-painter-s-palette](https://f.cloud.github.com/assets/3889965/1690885/d0dbcd42-5e55-11e3-8dc3-6e20c9e4d01e.jpg)

**Comment by richienyhus** [comment]
And we need a icon for Becasso's native file format.

Plus camera and light bulb which can be taken from Zumi's icons

**Comment by richienyhus** [comment]
![palette](https://f.cloud.github.com/assets/3889965/1692206/ddbbe49c-5e74-11e3-8ea5-775e0c690622.png)

3D icon from Zumi's website
http://zumi.xoom.it/myhaiku/system/index.html

**Comment by scottmc** [comment]
New icon added during GCI2016: 4c749af2094467701b1a182d03bbcea25c017823
