### ISSUE TITLE
Patch for Becasso

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Becasso#4]
Hi, I've made a patch for Becasso: with this patch now we can properly build Becasso on the recents Haiku's nightly builds. This patch will also remove the registration process (once built, Becasso will  result automaticaly registered).

You can find the patch here: https://bitbucket.org/haikuports/haikuports/issue/131/becasso-patch

**Comment by richienyhus** [comment]
Could you upload it here so we can turn it into a pull request?

https://gist.github.com (remember to mark it as a patch/diff in the gist web ui)

**Comment by ghost** [comment]
@Giova84 Hi, Do you happen to have your patch still? If so, maybe you can submit it here as the BitBucket repo was moved so afaik there's no way to retrieve your patch. Thank you!

**Comment by scottmc** [comment]
Seems this patch was lost, but seeing as it now builds on all Haiku platforms, going to close this out as resolved.  @Giova84 please read up on how to do pull requests and submit your future patches using them.
Fixed in 4552e03687c5851ced22c855496e8d483cc4ae35
